## - Hunting Pemain Basket -

<hr>

### Kriteria yang dipakai

- Usia (Age) <= 25 tahun,
- Tinggi badan (Height) >= 180 cm,
- Berat badan (Weight) <= 90 kg,
- Rata-rata point (Average points scored) >= 6, dan
- Rata-rata rebound (Average rebounds grabbed) >= 3.

<hr>

In [1]:
import pandas as pd
import numpy as np

from sklearn.linear_model import LinearRegression

In [2]:
nbaDf = pd.read_csv('all_seasons.csv')
nbaDf.head()

Unnamed: 0      player_name team_abbreviation   age  player_height  \
0           0   Chris Robinson               VAN  23.0         195.58   
1           1        Matt Fish               MIA  27.0         210.82   
2           2     Matt Bullard               HOU  30.0         208.28   
3           3     Marty Conlon               BOS  29.0         210.82   
4           4  Martin Muursepp               DAL  22.0         205.74   

   player_weight                    college country draft_year draft_round  \
0       90.71840           Western Kentucky     USA       1996           2   
1      106.59412  North Carolina-Wilmington     USA       1992           2   
2      106.59412                       Iowa     USA  Undrafted   Undrafted   
3      111.13004                 Providence     USA  Undrafted   Undrafted   
4      106.59412                       None     USA       1996           1   

   ...  pts  reb  ast  net_rating  oreb_pct  dreb_pct  usg_pct  ts_pct  \
0  ...  4.6  1.7  1.6       -11.4     0.039     0.088    0.155   0.486   
1  ...  0.3  0.8  0.0       -15.1     0.143     0.267    0.265   0.333   
2  ...  4.5  1.6  0.9         0.9     0.016     0.115    0.151   0.535   
3  ...  7.8  4.4  1.4        -9.0     0.083     0.152    0.167   0.542   
4  ...  3.7  1.6  0.5       -14.5     0.109     0.118    0.233   0.482   

   ast_pct   season  
0    0.156  1996-97  
1    0.000  1996-97  
2    0.099  1996-97  
3    0.101  1996-97  
4    0.114  1996-97  

[5 rows x 22 columns]

In [3]:
# Cek NA datasets
nbaDf.isnull().sum()

Unnamed: 0           0
player_name          0
team_abbreviation    0
age                  0
player_height        0
player_weight        0
college              0
country              0
draft_year           0
draft_round          0
draft_number         0
gp                   0
pts                  0
reb                  0
ast                  0
net_rating           0
oreb_pct             0
dreb_pct             0
usg_pct              0
ts_pct               0
ast_pct              0
season               0
dtype: int64

In [4]:
# Sortir parameter yang dipakai
newDf = nbaDf[['age', 'player_height', 'player_weight', 'pts', 'reb']]
newDf

age  player_height  player_weight   pts  reb
0     23.0         195.58       90.71840   4.6  1.7
1     27.0         210.82      106.59412   0.3  0.8
2     30.0         208.28      106.59412   4.5  1.6
3     29.0         210.82      111.13004   7.8  4.4
4     22.0         205.74      106.59412   3.7  1.6
...    ...            ...            ...   ...  ...
9556  29.0         200.66       97.52228   1.5  3.0
9557  23.0         193.04       83.91452  12.8  4.7
9558  25.0         220.98      120.20188   4.0  5.5
9559  23.0         210.82      108.86208   8.2  7.0
9560  30.0         203.20      102.05820  15.7  6.5

[9561 rows x 5 columns]

### Membuat DataFrame pemain Indonesia

In [5]:
IndoDf = pd.DataFrame({
    'Name': ['Andakara Prastawa Dyaksa', 'Reggie Mononimbar', 'Hardianus Lakudu', 'Kevin Yonas Sitorus', 'Arki Dikania Wisnu', 'Laurentius Steven Oei', 'Mei Joni', 'Vincent Rivaldi Kosasih', 'Hardian Wicaksono', 'Brandon Jawato'],
    'Club': ['Pelita Jaya Bakrie', 'Pelita Jaya Bakrie', 'Satria Muda Pertamina Jakarta', 'Satria Muda Pertamina Jakarta', 'Satria Muda Pertamina Jakarta', 'Satria Muda Pertamina Jakarta', 
             'Stapac', 'Stapac', 'Pacific Caesar Surabaya', 'Louvre Surabaya'],
    'Nationality': ['Indonesia', 'Indonesia', 'Indonesia', 'Indonesia', 'Indonesia', 'Indonesia', 'Indonesia', 'Indonesia', 'Indonesia', 'Indonesia'],
    'Age': [24, 21, 23, 26, 20, 21, 25, 23, 21, 24],
    'Height': [190, 185, 178, 185, 183, 191, 188, 179, 177, 182],
    'Weight': [90, 86, 83, 75, 80, 85, 90, 87, 80, 85],
    'Avg_points': [7, 6, 10, 11, 5, 4, 7, 1, 9, 6],
    'Avg_rebounds': [6, 3, 3, 4, 2, 10, 5, 2, 8, 5]
})

IndoDf

Name                           Club Nationality  Age  \
0  Andakara Prastawa Dyaksa             Pelita Jaya Bakrie   Indonesia   24   
1         Reggie Mononimbar             Pelita Jaya Bakrie   Indonesia   21   
2          Hardianus Lakudu  Satria Muda Pertamina Jakarta   Indonesia   23   
3       Kevin Yonas Sitorus  Satria Muda Pertamina Jakarta   Indonesia   26   
4        Arki Dikania Wisnu  Satria Muda Pertamina Jakarta   Indonesia   20   
5     Laurentius Steven Oei  Satria Muda Pertamina Jakarta   Indonesia   21   
6                  Mei Joni                         Stapac   Indonesia   25   
7   Vincent Rivaldi Kosasih                         Stapac   Indonesia   23   
8         Hardian Wicaksono        Pacific Caesar Surabaya   Indonesia   21   
9            Brandon Jawato                Louvre Surabaya   Indonesia   24   

   Height  Weight  Avg_points  Avg_rebounds  
0     190      90           7             6  
1     185      86           6             3  
2     178      83          10             3  
3     185      75          11             4  
4     183      80           5             2  
5     191      85           4            10  
6     188      90           7             5  
7     179      87           1             2  
8     177      80           9             8  
9     182      85           6             5

### - Membuat target sesuai kriteria -

In [6]:
# Filter pemain NBA sesuai kriteria
newDf['Target'] = newDf.apply(lambda x: 1 if (x['age'] <= 25) & (x['player_height'] >= 180) & (x['player_weight'] <= 90) & (x['pts'] >= 6) & (x['reb'] >= 3) else 0, axis=1)
newDf

C:\Users\Ans\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


age  player_height  player_weight   pts  reb  Target
0     23.0         195.58       90.71840   4.6  1.7       0
1     27.0         210.82      106.59412   0.3  0.8       0
2     30.0         208.28      106.59412   4.5  1.6       0
3     29.0         210.82      111.13004   7.8  4.4       0
4     22.0         205.74      106.59412   3.7  1.6       0
...    ...            ...            ...   ...  ...     ...
9556  29.0         200.66       97.52228   1.5  3.0       0
9557  23.0         193.04       83.91452  12.8  4.7       1
9558  25.0         220.98      120.20188   4.0  5.5       0
9559  23.0         210.82      108.86208   8.2  7.0       0
9560  30.0         203.20      102.05820  15.7  6.5       0

[9561 rows x 6 columns]

### - Train test split dan Standardize -

In [7]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

x = newDf[['age','player_height','player_weight', 'pts', 'reb']]
y = newDf['Target']

scaler = StandardScaler()
scaler.fit(x)
z = scaler.transform(x)
print(z)

xtr, xts, ytr, yts = train_test_split(x,y, test_size=.18, random_state=100)
print(xtr.shape)

[[-0.99674183 -0.57899275 -0.80260413 -0.58938997 -0.74785002]
 [-0.07727165  1.06312962  0.43960663 -1.31961423 -1.10871173]
 [ 0.61233098  0.78944256  0.43960663 -0.60637193 -0.78794577]
 ...
 [-0.53700674  2.15787786  1.50435871 -0.69128173  0.7757883 ]
 [-0.99674183  1.06312962  0.61706531  0.02196056  1.37722448]
 [ 0.61233098  0.24206844  0.08468927  1.29560752  1.17674575]]
(7840, 5)


<hr>

## Model Machine Learning

In [8]:
from sklearn.model_selection import RandomizedSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, accuracy_score, roc_auc_score, roc_curve
from sklearn import tree

### - LogisticRegression -

In [9]:
# param yang akan dituned LogisticRegression
penalty = ['l1', 'l2', 'elasticnet', 'none']
solver  = ['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga']
max_iter = [1, 10, 100, 1000, 10000]

param1 = {
    'penalty': penalty, 'solver': solver, 'max_iter': max_iter
}

In [10]:
model   = LogisticRegression()
modelrs = RandomizedSearchCV(
    estimator = model, param_distributions = param1
)

In [11]:
import warnings
warnings.simplefilter('ignore')

In [12]:
modelrs.fit(xtr, ytr)
modelrs.best_params_

{'solver': 'newton-cg', 'penalty': 'l2', 'max_iter': 1000}

In [13]:
model1 = LogisticRegression()
model1.fit(xtr, ytr)

model1Baru = LogisticRegression(solver='liblinear', penalty='l1', max_iter=1000)
model1Baru.fit(xtr, ytr)

print(f'LogisticRegression asli  : {model1.score(xts, yts)}')
print(f'LogisticRegression tuning: {model1Baru.score(xts, yts)}')

LogisticRegression asli  : 0.9872167344567112
LogisticRegression tuning: 0.9877977919814062


### - Random Forest -

In [14]:
# param yang akan dituned Random Forest

n_estimators = [1,10,100,1000]
criterion    = ['gini','entropy']
bootstrap    = [True,False]
         

param2 = {'criterion' : criterion,
          'bootstrap' : bootstrap,
          'n_estimators': n_estimators
         }

In [15]:
model2   = RandomForestClassifier()
modelrs2 = RandomizedSearchCV(
    estimator = model2, param_distributions = param2
)

In [16]:
modelrs2.fit(xtr, ytr)
modelrs2.best_params_

{'n_estimators': 1000, 'criterion': 'entropy', 'bootstrap': True}

In [17]:
model2 = RandomForestClassifier()
model2.fit(xtr, ytr)

model2Baru = RandomForestClassifier(
    n_estimators=10, criterion='gini', bootstrap=False
)
model2Baru.fit(xtr, ytr)

print(f'RandomForest asli  : {model2.score(xts, yts)}')
print(f'RandomForest tuning: {model2Baru.score(xts, yts)}')

RandomForest asli  : 0.999418942475305
RandomForest tuning: 1.0


### - Decision Tree -

In [18]:
param3 = {'criterion' : ['gini', 'entropy'], 'splitter' : ['best','random'], 'random_state' : [2,4,6,8,10]}

In [19]:
model3   = tree.DecisionTreeClassifier()
modelrs3 = RandomizedSearchCV(
    estimator = model3, param_distributions = param3
)

In [20]:
modelrs3.fit(xtr, ytr)
modelrs3.best_params_

{'splitter': 'best', 'random_state': 8, 'criterion': 'gini'}

In [21]:
model3 = tree.DecisionTreeClassifier()
model3.fit(xtr, ytr)

model3Baru = tree.DecisionTreeClassifier(splitter= 'best', criterion= 'gini', random_state=4)
model3Baru.fit(xtr, ytr)

print(f'DecisionTree asli  : {model3.score(xts, yts)}')
print(f'DecisionTree tuning: {model3Baru.score(xts, yts)}')

DecisionTree asli  : 1.0
DecisionTree tuning: 1.0


## Evaluation Matrics
Balanced Accuracy, Precision, Recall, F1 score & ROC-AUC score

In [22]:
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import roc_curve, roc_auc_score

- Logistic Regression

In [23]:
y_pred_log = model1.predict(xts)
print('Balanced-Acc : ', round(balanced_accuracy_score(yts, y_pred_log)*100,2), '%')
print('Precision(+) : ', round(precision_score(yts, y_pred_log, pos_label=1)*100,2), '%')
print('Precision(-) : ', round(precision_score(yts, y_pred_log, pos_label=0)*100,2), '%')
print('Recall(+)    : ', round(recall_score(yts, y_pred_log, pos_label=1)*100,2), '%')
print('Recall(-)    : ', round(recall_score(yts, y_pred_log, pos_label=0)*100,2), '%')
print('F1 score(+)  : ', round(f1_score(yts, y_pred_log, pos_label=1)*100,2), '%')
print('F1 score(-)  : ', round(f1_score(yts, y_pred_log, pos_label=0)*100,2), '%')
print('Nilai AUC    : ', round(roc_auc_score(yts, y_pred_log)*100,2), '%')

Balanced-Acc :  70.19 %
Precision(+) :  50.0 %
Precision(-) :  99.24 %
Recall(+)    :  40.91 %
Recall(-)    :  99.47 %
F1 score(+)  :  45.0 %
F1 score(-)  :  99.35 %
Nilai AUC    :  70.19 %


- Random Forest

In [24]:
y_pred_log = model2.predict(xts)
print('Balanced-Acc : ', round(balanced_accuracy_score(yts, y_pred_log)*100,2), '%')
print('Precision(+) : ', round(precision_score(yts, y_pred_log, pos_label=1)*100,2), '%')
print('Precision(-) : ', round(precision_score(yts, y_pred_log, pos_label=0)*100,2), '%')
print('Recall(+)    : ', round(recall_score(yts, y_pred_log, pos_label=1)*100,2), '%')
print('Recall(-)    : ', round(recall_score(yts, y_pred_log, pos_label=0)*100,2), '%')
print('F1 score(+)  : ', round(f1_score(yts, y_pred_log, pos_label=1)*100,2), '%')
print('F1 score(-)  : ', round(f1_score(yts, y_pred_log, pos_label=0)*100,2), '%')
print('Nilai AUC    : ', round(roc_auc_score(yts, y_pred_log)*100,2), '%')

Balanced-Acc :  99.97 %
Precision(+) :  95.65 %
Precision(-) :  100.0 %
Recall(+)    :  100.0 %
Recall(-)    :  99.94 %
F1 score(+)  :  97.78 %
F1 score(-)  :  99.97 %
Nilai AUC    :  99.97 %


- Decision Tree

In [25]:
y_pred_log = model3.predict(xts)
print('Balanced-Acc : ', round(balanced_accuracy_score(yts, y_pred_log)*100,2), '%')
print('Precision(+) : ', round(precision_score(yts, y_pred_log, pos_label=1)*100,2), '%')
print('Precision(-) : ', round(precision_score(yts, y_pred_log, pos_label=0)*100,2), '%')
print('Recall(+)    : ', round(recall_score(yts, y_pred_log, pos_label=1)*100,2), '%')
print('Recall(-)    : ', round(recall_score(yts, y_pred_log, pos_label=0)*100,2), '%')
print('F1 score(+)  : ', round(f1_score(yts, y_pred_log, pos_label=1)*100,2), '%')
print('F1 score(-)  : ', round(f1_score(yts, y_pred_log, pos_label=0)*100,2), '%')
print('Nilai AUC    : ', round(roc_auc_score(yts, y_pred_log)*100,2), '%')

Balanced-Acc :  100.0 %
Precision(+) :  100.0 %
Precision(-) :  100.0 %
Recall(+)    :  100.0 %
Recall(-)    :  100.0 %
F1 score(+)  :  100.0 %
F1 score(-)  :  100.0 %
Nilai AUC    :  100.0 %


### Dari 3 model machine learning dan evaluation matrics, diambil Decision Tree

In [26]:
IndoDf["Recommendation"] = model3Baru.predict(IndoDf[["Age", "Height", "Weight", "Avg_points", "Avg_rebounds"]])
IndoDf

Name                           Club Nationality  Age  \
0  Andakara Prastawa Dyaksa             Pelita Jaya Bakrie   Indonesia   24   
1         Reggie Mononimbar             Pelita Jaya Bakrie   Indonesia   21   
2          Hardianus Lakudu  Satria Muda Pertamina Jakarta   Indonesia   23   
3       Kevin Yonas Sitorus  Satria Muda Pertamina Jakarta   Indonesia   26   
4        Arki Dikania Wisnu  Satria Muda Pertamina Jakarta   Indonesia   20   
5     Laurentius Steven Oei  Satria Muda Pertamina Jakarta   Indonesia   21   
6                  Mei Joni                         Stapac   Indonesia   25   
7   Vincent Rivaldi Kosasih                         Stapac   Indonesia   23   
8         Hardian Wicaksono        Pacific Caesar Surabaya   Indonesia   21   
9            Brandon Jawato                Louvre Surabaya   Indonesia   24   

   Height  Weight  Avg_points  Avg_rebounds  Recommendation  
0     190      90           7             6               1  
1     185      86           6             3               1  
2     178      83          10             3               0  
3     185      75          11             4               0  
4     183      80           5             2               0  
5     191      85           4            10               0  
6     188      90           7             5               1  
7     179      87           1             2               0  
8     177      80           9             8               0  
9     182      85           6             5               1

<hr>

## - Pemain yang lolos seleksi -

In [27]:
rekrut = IndoDf[IndoDf['Recommendation'] == 1]
rekrut

Name                Club Nationality  Age  Height  \
0  Andakara Prastawa Dyaksa  Pelita Jaya Bakrie   Indonesia   24     190   
1         Reggie Mononimbar  Pelita Jaya Bakrie   Indonesia   21     185   
6                  Mei Joni              Stapac   Indonesia   25     188   
9            Brandon Jawato     Louvre Surabaya   Indonesia   24     182   

   Weight  Avg_points  Avg_rebounds  Recommendation  
0      90           7             6               1  
1      86           6             3               1  
6      90           7             5               1  
9      85           6             5               1